// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package main
//
//import (
//	json "encoding/json"
//	easyjson "github.com/mailru/easyjson"
//	jlexer "github.com/mailru/easyjson/jlexer"
//	jwriter "github.com/mailru/easyjson/jwriter"
//)
//
//// suppress unused package warning
//var (
//	_ *json.RawMessage
//	_ *jlexer.Lexer
//	_ *jwriter.Writer
//	_ easyjson.Marshaler
//)
//
//func easyjson6a975c40DecodeGoBootCampGoPerformanceSupportJson(in *jlexer.Lexer, out *User) {
//	isTopLevel := in.IsStart()
//	if in.IsNull() {
//		if isTopLevel {
//			in.Consumed()
//		}
//		in.Skip()
//		return
//	}
//	in.Delim('{')
//	for !in.IsDelim('}') {
//		key := in.UnsafeString()
//		in.WantColon()
//		if in.IsNull() {
//			in.Skip()
//			in.WantComma()
//			continue
//		}
//		switch key {
//		case "name":
//			out.Name = string(in.String())
//		case "age":
//			out.Age = int(in.Int())
//		case "children":
//			if in.IsNull() {
//				in.Skip()
//				out.Children = nil
//			} else {
//				in.Delim('[')
//				if out.Children == nil {
//					if !in.IsDelim(']') {
//						out.Children = make([]User, 0, 1)
//					} else {
//						out.Children = []User{}
//					}
//				} else {
//					out.Children = (out.Children)[:0]
//				}
//				for !in.IsDelim(']') {
//					var v1 User
//					(v1).UnmarshalEasyJSON(in)
//					out.Children = append(out.Children, v1)
//					in.WantComma()
//				}
//				in.Delim(']')
//			}
//		default:
//			in.SkipRecursive()
//		}
//		in.WantComma()
//	}
//	in.Delim('}')
//	if isTopLevel {
//		in.Consumed()
//	}
//}
//func easyjson6a975c40EncodeGoBootCampGoPerformanceSupportJson(out *jwriter.Writer, in User) {
//	out.RawByte('{')
//	first := true
//	_ = first
//	if !first {
//		out.RawByte(',')
//	}
//	first = false
//	out.RawString("\"name\":")
//	out.String(string(in.Name))
//	if !first {
//		out.RawByte(',')
//	}
//	first = false
//	out.RawString("\"age\":")
//	out.Int(int(in.Age))
//	if !first {
//		out.RawByte(',')
//	}
//	first = false
//	out.RawString("\"children\":")
//	if in.Children == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
//		out.RawString("null")
//	} else {
//		out.RawByte('[')
//		for v2, v3 := range in.Children {
//			if v2 > 0 {
//				out.RawByte(',')
//			}
//			(v3).MarshalEasyJSON(out)
//		}
//		out.RawByte(']')
//	}
//	out.RawByte('}')
//}
//
//// MarshalJSON supports json.Marshaler interface
//func (v User) MarshalJSON() ([]byte, error) {
//	w := jwriter.Writer{}
//	easyjson6a975c40EncodeGoBootCampGoPerformanceSupportJson(&w, v)
//	return w.Buffer.BuildBytes(), w.Error
//}
//
//// MarshalEasyJSON supports easyjson.Marshaler interface
//func (v User) MarshalEasyJSON(w *jwriter.Writer) {
//	easyjson6a975c40EncodeGoBootCampGoPerformanceSupportJson(w, v)
//}
//
//// UnmarshalJSON supports json.Unmarshaler interface
//func (v *User) UnmarshalJSON(data []byte) error {
//	r := jlexer.Lexer{Data: data}
//	easyjson6a975c40DecodeGoBootCampGoPerformanceSupportJson(&r, v)
//	return r.Error()
//}
//
//// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
//func (v *User) UnmarshalEasyJSON(l *jlexer.Lexer) {
//	easyjson6a975c40DecodeGoBootCampGoPerformanceSupportJson(l, v)
//}
//func easyjson6a975c40DecodeGoBootCampGoPerformanceSupportJson1(in *jlexer.Lexer, out *Task) {
//	isTopLevel := in.IsStart()
//	if in.IsNull() {
//		if isTopLevel {
//			in.Consumed()
//		}
//		in.Skip()
//		return
//	}
//	in.Delim('{')
//	for !in.IsDelim('}') {
//		key := in.UnsafeString()
//		in.WantColon()
//		if in.IsNull() {
//			in.Skip()
//			in.WantComma()
//			continue
//		}
//		switch key {
//		case "title":
//			out.Title = string(in.String())
//		case "done":
//			out.Done = bool(in.Bool())
//		case "important":
//			out.Important = bool(in.Bool())
//		default:
//			in.SkipRecursive()
//		}
//		in.WantComma()
//	}
//	in.Delim('}')
//	if isTopLevel {
//		in.Consumed()
//	}
//}
//func easyjson6a975c40EncodeGoBootCampGoPerformanceSupportJson1(out *jwriter.Writer, in Task) {
//	out.RawByte('{')
//	first := true
//	_ = first
//	if !first {
//		out.RawByte(',')
//	}
//	first = false
//	out.RawString("\"title\":")
//	out.String(string(in.Title))
//	if !first {
//		out.RawByte(',')
//	}
//	first = false
//	out.RawString("\"done\":")
//	out.Bool(bool(in.Done))
//	if !first {
//		out.RawByte(',')
//	}
//	first = false
//	out.RawString("\"important\":")
//	out.Bool(bool(in.Important))
//	out.RawByte('}')
//}
//
//// MarshalJSON supports json.Marshaler interface
//func (v Task) MarshalJSON() ([]byte, error) {
//	w := jwriter.Writer{}
//	easyjson6a975c40EncodeGoBootCampGoPerformanceSupportJson1(&w, v)
//	return w.Buffer.BuildBytes(), w.Error
//}
//
//// MarshalEasyJSON supports easyjson.Marshaler interface
//func (v Task) MarshalEasyJSON(w *jwriter.Writer) {
//	easyjson6a975c40EncodeGoBootCampGoPerformanceSupportJson1(w, v)
//}
//
//// UnmarshalJSON supports json.Unmarshaler interface
//func (v *Task) UnmarshalJSON(data []byte) error {
//	r := jlexer.Lexer{Data: data}
//	easyjson6a975c40DecodeGoBootCampGoPerformanceSupportJson1(&r, v)
//	return r.Error()
//}
//
//// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
//func (v *Task) UnmarshalEasyJSON(l *jlexer.Lexer) {
//	easyjson6a975c40DecodeGoBootCampGoPerformanceSupportJson1(l, v)
//}
//func easyjson6a975c40DecodeGoBootCampGoPerformanceSupportJson2(in *jlexer.Lexer, out *Json) {
//	isTopLevel := in.IsStart()
//	if in.IsNull() {
//		if isTopLevel {
//			in.Consumed()
//		}
//		in.Skip()
//		return
//	}
//	in.Delim('{')
//	for !in.IsDelim('}') {
//		key := in.UnsafeString()
//		in.WantColon()
//		if in.IsNull() {
//			in.Skip()
//			in.WantComma()
//			continue
//		}
//		switch key {
//		case "user":
//			(out.User).UnmarshalEasyJSON(in)
//		case "auth":
//			easyjson6a975c40Decode(in, &out.Auth)
//		case "Tasks":
//			if in.IsNull() {
//				in.Skip()
//				out.Tasks = nil
//			} else {
//				in.Delim('[')
//				if out.Tasks == nil {
//					if !in.IsDelim(']') {
//						out.Tasks = make([]Task, 0, 2)
//					} else {
//						out.Tasks = []Task{}
//					}
//				} else {
//					out.Tasks = (out.Tasks)[:0]
//				}
//				for !in.IsDelim(']') {
//					var v4 Task
//					(v4).UnmarshalEasyJSON(in)
//					out.Tasks = append(out.Tasks, v4)
//					in.WantComma()
//				}
//				in.Delim(']')
//			}
//		default:
//			in.SkipRecursive()
//		}
//		in.WantComma()
//	}
//	in.Delim('}')
//	if isTopLevel {
//		in.Consumed()
//	}
//}
//func easyjson6a975c40EncodeGoBootCampGoPerformanceSupportJson2(out *jwriter.Writer, in Json) {
//	out.RawByte('{')
//	first := true
//	_ = first
//	if !first {
//		out.RawByte(',')
//	}
//	first = false
//	out.RawString("\"user\":")
//	(in.User).MarshalEasyJSON(out)
//	if !first {
//		out.RawByte(',')
//	}
//	first = false
//	out.RawString("\"auth\":")
//	easyjson6a975c40Encode(out, in.Auth)
//	if !first {
//		out.RawByte(',')
//	}
//	first = false
//	out.RawString("\"Tasks\":")
//	if in.Tasks == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
//		out.RawString("null")
//	} else {
//		out.RawByte('[')
//		for v5, v6 := range in.Tasks {
//			if v5 > 0 {
//				out.RawByte(',')
//			}
//			(v6).MarshalEasyJSON(out)
//		}
//		out.RawByte(']')
//	}
//	out.RawByte('}')
//}
//
//// MarshalJSON supports json.Marshaler interface
//func (v Json) MarshalJSON() ([]byte, error) {
//	w := jwriter.Writer{}
//	easyjson6a975c40EncodeGoBootCampGoPerformanceSupportJson2(&w, v)
//	return w.Buffer.BuildBytes(), w.Error
//}
//
//// MarshalEasyJSON supports easyjson.Marshaler interface
//func (v Json) MarshalEasyJSON(w *jwriter.Writer) {
//	easyjson6a975c40EncodeGoBootCampGoPerformanceSupportJson2(w, v)
//}
//
//// UnmarshalJSON supports json.Unmarshaler interface
//func (v *Json) UnmarshalJSON(data []byte) error {
//	r := jlexer.Lexer{Data: data}
//	easyjson6a975c40DecodeGoBootCampGoPerformanceSupportJson2(&r, v)
//	return r.Error()
//}
//
//// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
//func (v *Json) UnmarshalEasyJSON(l *jlexer.Lexer) {
//	easyjson6a975c40DecodeGoBootCampGoPerformanceSupportJson2(l, v)
//}
//func easyjson6a975c40Decode(in *jlexer.Lexer, out *struct {
//	SessionID string `json:"session_id"`
//	CsrfToken string `json:"csrf_token"`
//}) {
//	isTopLevel := in.IsStart()
//	if in.IsNull() {
//		if isTopLevel {
//			in.Consumed()
//		}
//		in.Skip()
//		return
//	}
//	in.Delim('{')
//	for !in.IsDelim('}') {
//		key := in.UnsafeString()
//		in.WantColon()
//		if in.IsNull() {
//			in.Skip()
//			in.WantComma()
//			continue
//		}
//		switch key {
//		case "session_id":
//			out.SessionID = string(in.String())
//		case "csrf_token":
//			out.CsrfToken = string(in.String())
//		default:
//			in.SkipRecursive()
//		}
//		in.WantComma()
//	}
//	in.Delim('}')
//	if isTopLevel {
//		in.Consumed()
//	}
//}
//func easyjson6a975c40Encode(out *jwriter.Writer, in struct {
//	SessionID string `json:"session_id"`
//	CsrfToken string `json:"csrf_token"`
//}) {
//	out.RawByte('{')
//	first := true
//	_ = first
//	if !first {
//		out.RawByte(',')
//	}
//	first = false
//	out.RawString("\"session_id\":")
//	out.String(string(in.SessionID))
//	if !first {
//		out.RawByte(',')
//	}
//	first = false
//	out.RawString("\"csrf_token\":")
//	out.String(string(in.CsrfToken))
//	out.RawByte('}')
//}
